// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.account.modelo;

import br.com.bufunfa.finance.account.modelo.AccountSystem;
import br.com.bufunfa.finance.account.repository.AccountSystemRepository;
import br.com.bufunfa.finance.account.service.AccountSystemService;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AccountSystemDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AccountSystemDataOnDemand: @Component;
    
    private Random AccountSystemDataOnDemand.rnd = new SecureRandom();
    
    private List<AccountSystem> AccountSystemDataOnDemand.data;
    
    @Autowired
    AccountSystemService AccountSystemDataOnDemand.accountSystemService;
    
    @Autowired
    AccountSystemRepository AccountSystemDataOnDemand.accountSystemRepository;
    
    public AccountSystem AccountSystemDataOnDemand.getNewTransientAccountSystem(int index) {
        AccountSystem obj = new AccountSystem();
        setName(obj, index);
        setRootAccountId(obj, index);
        return obj;
    }
    
    public void AccountSystemDataOnDemand.setName(AccountSystem obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void AccountSystemDataOnDemand.setRootAccountId(AccountSystem obj, int index) {
        Long rootAccountId = new Integer(index).longValue();
        obj.setRootAccountId(rootAccountId);
    }
    
    public AccountSystem AccountSystemDataOnDemand.getSpecificAccountSystem(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        AccountSystem obj = data.get(index);
        java.lang.Long id = obj.getId();
        return accountSystemService.findAccountSystem(id);
    }
    
    public AccountSystem AccountSystemDataOnDemand.getRandomAccountSystem() {
        init();
        AccountSystem obj = data.get(rnd.nextInt(data.size()));
        java.lang.Long id = obj.getId();
        return accountSystemService.findAccountSystem(id);
    }
    
    public boolean AccountSystemDataOnDemand.modifyAccountSystem(AccountSystem obj) {
        return false;
    }
    
    public void AccountSystemDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = accountSystemService.findAccountSystemEntries(from, to);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'AccountSystem' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<br.com.bufunfa.finance.account.modelo.AccountSystem>();
        for (int i = 0; i < 10; i++) {
            AccountSystem obj = getNewTransientAccountSystem(i);
            try {
                accountSystemService.saveAccountSystem(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            accountSystemRepository.flush();
            data.add(obj);
        }
    }
    
}
