// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.account.modelo;

import br.com.bufunfa.finance.account.modelo.AccountSystemDataOnDemand;
import br.com.bufunfa.finance.account.repository.AccountSystemRepository;
import br.com.bufunfa.finance.account.service.AccountSystemService;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AccountSystemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AccountSystemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AccountSystemIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AccountSystemIntegrationTest: @Transactional;
    
    @Autowired
    private AccountSystemDataOnDemand AccountSystemIntegrationTest.dod;
    
    @Autowired
    AccountSystemService AccountSystemIntegrationTest.accountSystemService;
    
    @Autowired
    AccountSystemRepository AccountSystemIntegrationTest.accountSystemRepository;
    
    @Test
    public void AccountSystemIntegrationTest.testCountAllAccountSystems() {
        Assert.assertNotNull("Data on demand for 'AccountSystem' failed to initialize correctly", dod.getRandomAccountSystem());
        long count = accountSystemService.countAllAccountSystems();
        Assert.assertTrue("Counter for 'AccountSystem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AccountSystemIntegrationTest.testFindAccountSystem() {
        AccountSystem obj = dod.getRandomAccountSystem();
        Assert.assertNotNull("Data on demand for 'AccountSystem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AccountSystem' failed to provide an identifier", id);
        obj = accountSystemService.findAccountSystem(id);
        Assert.assertNotNull("Find method for 'AccountSystem' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AccountSystem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AccountSystemIntegrationTest.testFindAllAccountSystems() {
        Assert.assertNotNull("Data on demand for 'AccountSystem' failed to initialize correctly", dod.getRandomAccountSystem());
        long count = accountSystemService.countAllAccountSystems();
        Assert.assertTrue("Too expensive to perform a find all test for 'AccountSystem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AccountSystem> result = accountSystemService.findAllAccountSystems();
        Assert.assertNotNull("Find all method for 'AccountSystem' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AccountSystem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AccountSystemIntegrationTest.testFindAccountSystemEntries() {
        Assert.assertNotNull("Data on demand for 'AccountSystem' failed to initialize correctly", dod.getRandomAccountSystem());
        long count = accountSystemService.countAllAccountSystems();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AccountSystem> result = accountSystemService.findAccountSystemEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AccountSystem' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AccountSystem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AccountSystemIntegrationTest.testFlush() {
        AccountSystem obj = dod.getRandomAccountSystem();
        Assert.assertNotNull("Data on demand for 'AccountSystem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AccountSystem' failed to provide an identifier", id);
        obj = accountSystemService.findAccountSystem(id);
        Assert.assertNotNull("Find method for 'AccountSystem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAccountSystem(obj);
        Integer currentVersion = obj.getVersion();
        accountSystemRepository.flush();
        Assert.assertTrue("Version for 'AccountSystem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AccountSystemIntegrationTest.testUpdateAccountSystemUpdate() {
        AccountSystem obj = dod.getRandomAccountSystem();
        Assert.assertNotNull("Data on demand for 'AccountSystem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AccountSystem' failed to provide an identifier", id);
        obj = accountSystemService.findAccountSystem(id);
        boolean modified =  dod.modifyAccountSystem(obj);
        Integer currentVersion = obj.getVersion();
        AccountSystem merged = accountSystemService.updateAccountSystem(obj);
        accountSystemRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AccountSystem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AccountSystemIntegrationTest.testSaveAccountSystem() {
        Assert.assertNotNull("Data on demand for 'AccountSystem' failed to initialize correctly", dod.getRandomAccountSystem());
        AccountSystem obj = dod.getNewTransientAccountSystem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AccountSystem' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AccountSystem' identifier to be null", obj.getId());
        accountSystemService.saveAccountSystem(obj);
        accountSystemRepository.flush();
        Assert.assertNotNull("Expected 'AccountSystem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AccountSystemIntegrationTest.testDeleteAccountSystem() {
        AccountSystem obj = dod.getRandomAccountSystem();
        Assert.assertNotNull("Data on demand for 'AccountSystem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AccountSystem' failed to provide an identifier", id);
        obj = accountSystemService.findAccountSystem(id);
        accountSystemService.deleteAccountSystem(obj);
        accountSystemRepository.flush();
        Assert.assertNull("Failed to remove 'AccountSystem' with identifier '" + id + "'", accountSystemService.findAccountSystem(id));
    }
    
}
