// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.account.ui.jsf.config;

import br.com.bufunfa.finance.account.ui.jsf.config.AccountViewNames;

privileged aspect AccountViewNames_Roo_JavaBean {
    
    public String AccountViewNames.getTitleId() {
        return this.titleId;
    }
    
    public void AccountViewNames.setTitleId(String titleId) {
        this.titleId = titleId;
    }
    
    public String AccountViewNames.getTitlePage() {
        return this.titlePage;
    }
    
    public void AccountViewNames.setTitlePage(String titlePage) {
        this.titlePage = titlePage;
    }
    
    public String AccountViewNames.getPanelUserinfo() {
        return this.panelUserinfo;
    }
    
    public void AccountViewNames.setPanelUserinfo(String panelUserinfo) {
        this.panelUserinfo = panelUserinfo;
    }
    
    public String AccountViewNames.getPanelMessages() {
        return this.panelMessages;
    }
    
    public void AccountViewNames.setPanelMessages(String panelMessages) {
        this.panelMessages = panelMessages;
    }
    
}
