// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.account.ui.jsf.config;

import br.com.bufunfa.finance.account.ui.jsf.config.TransactionViewNames;

privileged aspect TransactionViewNames_Roo_JavaBean {
    
    public String TransactionViewNames.getTitlePage() {
        return this.titlePage;
    }
    
    public void TransactionViewNames.setTitlePage(String titlePage) {
        this.titlePage = titlePage;
    }
    
    public String TransactionViewNames.getTitleId() {
        return this.titleId;
    }
    
    public void TransactionViewNames.setTitleId(String titleId) {
        this.titleId = titleId;
    }
    
    public String TransactionViewNames.getInputFromAccount() {
        return this.inputFromAccount;
    }
    
    public void TransactionViewNames.setInputFromAccount(String inputFromAccount) {
        this.inputFromAccount = inputFromAccount;
    }
    
    public String TransactionViewNames.getInputToAccount() {
        return this.inputToAccount;
    }
    
    public void TransactionViewNames.setInputToAccount(String inputToAccount) {
        this.inputToAccount = inputToAccount;
    }
    
    public String TransactionViewNames.getInputDate() {
        return this.inputDate;
    }
    
    public void TransactionViewNames.setInputDate(String inputDate) {
        this.inputDate = inputDate;
    }
    
    public String TransactionViewNames.getInputValue() {
        return this.inputValue;
    }
    
    public void TransactionViewNames.setInputValue(String inputValue) {
        this.inputValue = inputValue;
    }
    
    public String TransactionViewNames.getInputComment() {
        return this.inputComment;
    }
    
    public void TransactionViewNames.setInputComment(String inputComment) {
        this.inputComment = inputComment;
    }
    
    public String TransactionViewNames.getButtonSaveTransaction() {
        return this.buttonSaveTransaction;
    }
    
    public void TransactionViewNames.setButtonSaveTransaction(String buttonSaveTransaction) {
        this.buttonSaveTransaction = buttonSaveTransaction;
    }
    
    public String TransactionViewNames.getFormTransaction() {
        return this.formTransaction;
    }
    
    public void TransactionViewNames.setFormTransaction(String formTransaction) {
        this.formTransaction = formTransaction;
    }
    
    public String TransactionViewNames.getTransactionPageTestURL() {
        return this.transactionPageTestURL;
    }
    
    public void TransactionViewNames.setTransactionPageTestURL(String transactionPageTestURL) {
        this.transactionPageTestURL = transactionPageTestURL;
    }
    
    public String TransactionViewNames.getPanelMessages() {
        return this.panelMessages;
    }
    
    public void TransactionViewNames.setPanelMessages(String panelMessages) {
        this.panelMessages = panelMessages;
    }
    
}
