// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.ui.account;

import br.com.bufunfa.finance.ui.account.AccountTreeUI;
import java.io.Serializable;

privileged aspect AccountTreeUI_Roo_Serializable {
    
    declare parents: AccountTreeUI implements Serializable;
    
    private static final long AccountTreeUI.serialVersionUID = 1L;
    
}
