// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.user.ui.jsf.config;

import br.com.bufunfa.finance.user.ui.jsf.config.UserViewNames;

privileged aspect UserViewNames_Roo_JavaBean {
    
    public String UserViewNames.getTitle() {
        return this.title;
    }
    
    public void UserViewNames.setTitle(String title) {
        this.title = title;
    }
    
    public String UserViewNames.getTitlePage() {
        return this.titlePage;
    }
    
    public void UserViewNames.setTitlePage(String titlePage) {
        this.titlePage = titlePage;
    }
    
    public String UserViewNames.getTitleId() {
        return this.titleId;
    }
    
    public void UserViewNames.setTitleId(String titleId) {
        this.titleId = titleId;
    }
    
    public String UserViewNames.getFormUser() {
        return this.formUser;
    }
    
    public void UserViewNames.setFormUser(String formUser) {
        this.formUser = formUser;
    }
    
    public String UserViewNames.getLabelUserEmail() {
        return this.labelUserEmail;
    }
    
    public void UserViewNames.setLabelUserEmail(String labelUserEmail) {
        this.labelUserEmail = labelUserEmail;
    }
    
    public String UserViewNames.getLabelUserPassword() {
        return this.labelUserPassword;
    }
    
    public void UserViewNames.setLabelUserPassword(String labelUserPassword) {
        this.labelUserPassword = labelUserPassword;
    }
    
    public String UserViewNames.getInputUserEmail() {
        return this.inputUserEmail;
    }
    
    public void UserViewNames.setInputUserEmail(String inputUserEmail) {
        this.inputUserEmail = inputUserEmail;
    }
    
    public String UserViewNames.getInputUserPassword() {
        return this.inputUserPassword;
    }
    
    public void UserViewNames.setInputUserPassword(String inputUserPassword) {
        this.inputUserPassword = inputUserPassword;
    }
    
    public String UserViewNames.getButtonSaveNewUser() {
        return this.buttonSaveNewUser;
    }
    
    public void UserViewNames.setButtonSaveNewUser(String buttonSaveNewUser) {
        this.buttonSaveNewUser = buttonSaveNewUser;
    }
    
    public String UserViewNames.getButtonCancelNewUser() {
        return this.buttonCancelNewUser;
    }
    
    public void UserViewNames.setButtonCancelNewUser(String buttonCancelNewUser) {
        this.buttonCancelNewUser = buttonCancelNewUser;
    }
    
    public String UserViewNames.getButtonLoginUser() {
        return this.buttonLoginUser;
    }
    
    public void UserViewNames.setButtonLoginUser(String buttonLoginUser) {
        this.buttonLoginUser = buttonLoginUser;
    }
    
    public String UserViewNames.getUserPageTestURL() {
        return this.userPageTestURL;
    }
    
    public void UserViewNames.setUserPageTestURL(String userPageTestURL) {
        this.userPageTestURL = userPageTestURL;
    }
    
    public String UserViewNames.getWebDriverType() {
        return this.webDriverType;
    }
    
    public void UserViewNames.setWebDriverType(String webDriverType) {
        this.webDriverType = webDriverType;
    }
    
    public String UserViewNames.getPanelMessages() {
        return this.panelMessages;
    }
    
    public void UserViewNames.setPanelMessages(String panelMessages) {
        this.panelMessages = panelMessages;
    }
    
    public String UserViewNames.getMessageValidEmailRequired() {
        return this.messageValidEmailRequired;
    }
    
    public void UserViewNames.setMessageValidEmailRequired(String messageValidEmailRequired) {
        this.messageValidEmailRequired = messageValidEmailRequired;
    }
    
    public String UserViewNames.getMessagePasswordRequired() {
        return this.messagePasswordRequired;
    }
    
    public void UserViewNames.setMessagePasswordRequired(String messagePasswordRequired) {
        this.messagePasswordRequired = messagePasswordRequired;
    }
    
    public String UserViewNames.getMessageEmailAlreadyExists() {
        return this.messageEmailAlreadyExists;
    }
    
    public void UserViewNames.setMessageEmailAlreadyExists(String messageEmailAlreadyExists) {
        this.messageEmailAlreadyExists = messageEmailAlreadyExists;
    }
    
    public String UserViewNames.getMessageInvalidUserCredentials() {
        return this.messageInvalidUserCredentials;
    }
    
    public void UserViewNames.setMessageInvalidUserCredentials(String messageInvalidUserCredentials) {
        this.messageInvalidUserCredentials = messageInvalidUserCredentials;
    }
    
}
