// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.user.ui.jsf.config;

import br.com.bufunfa.finance.user.ui.jsf.config.UserViewNames;

privileged aspect UserViewNames_Roo_JavaBean {
    
    public String UserViewNames.getFormNewUser() {
        return this.formNewUser;
    }
    
    public void UserViewNames.setFormNewUser(String formNewUser) {
        this.formNewUser = formNewUser;
    }
    
    public String UserViewNames.getLabelUserEmail() {
        return this.labelUserEmail;
    }
    
    public void UserViewNames.setLabelUserEmail(String labelUserEmail) {
        this.labelUserEmail = labelUserEmail;
    }
    
    public String UserViewNames.getLabelUserPassword() {
        return this.labelUserPassword;
    }
    
    public void UserViewNames.setLabelUserPassword(String labelUserPassword) {
        this.labelUserPassword = labelUserPassword;
    }
    
    public String UserViewNames.getInputUserEmail() {
        return this.inputUserEmail;
    }
    
    public void UserViewNames.setInputUserEmail(String inputUserEmail) {
        this.inputUserEmail = inputUserEmail;
    }
    
    public String UserViewNames.getInputUserPassword() {
        return this.inputUserPassword;
    }
    
    public void UserViewNames.setInputUserPassword(String inputUserPassword) {
        this.inputUserPassword = inputUserPassword;
    }
    
    public String UserViewNames.getButtonSaveNewUser() {
        return this.buttonSaveNewUser;
    }
    
    public void UserViewNames.setButtonSaveNewUser(String buttonSaveNewUser) {
        this.buttonSaveNewUser = buttonSaveNewUser;
    }
    
    public String UserViewNames.getButtonCancelNewUser() {
        return this.buttonCancelNewUser;
    }
    
    public void UserViewNames.setButtonCancelNewUser(String buttonCancelNewUser) {
        this.buttonCancelNewUser = buttonCancelNewUser;
    }
    
    public String UserViewNames.getUserPageTestURL() {
        return this.userPageTestURL;
    }
    
    public void UserViewNames.setUserPageTestURL(String userPageTestURL) {
        this.userPageTestURL = userPageTestURL;
    }
    
    public String UserViewNames.getWebDriverType() {
        return this.webDriverType;
    }
    
    public void UserViewNames.setWebDriverType(String webDriverType) {
        this.webDriverType = webDriverType;
    }
    
    public String UserViewNames.getPanelMessages() {
        return this.panelMessages;
    }
    
    public void UserViewNames.setPanelMessages(String panelMessages) {
        this.panelMessages = panelMessages;
    }
    
}
