// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.account.controller;

import br.com.bufunfa.finance.account.controller.AccountTreeItemUI;
import java.io.Serializable;

privileged aspect AccountTreeItemUI_Roo_Serializable {
    
    declare parents: AccountTreeItemUI implements Serializable;
    
}
