// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.account.service.validation;

import java.lang.Long;

privileged aspect TransactionParameters_Roo_JavaBean {
    
    public Long TransactionParameters.getOriginAccountId() {
        return this.originAccountId;
    }
    
    public void TransactionParameters.setOriginAccountId(Long originAccountId) {
        this.originAccountId = originAccountId;
    }
    
}
