// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.account.service.validation;

import java.util.Date;

privileged aspect TransactionQueryParameters_Roo_JavaBean {
    
    public Date TransactionQueryParameters.getBeginDate() {
        return this.beginDate;
    }
    
    public void TransactionQueryParameters.setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }
    
    public Date TransactionQueryParameters.getEndDate() {
        return this.endDate;
    }
    
    public void TransactionQueryParameters.setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    
}
