// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.user.modelo;

import br.com.bufunfa.finance.user.modelo.User;
import java.io.Serializable;

privileged aspect User_Roo_Serializable {
    
    declare parents: User implements Serializable;
    
    private static final long User.serialVersionUID = 1L;
    
}
