// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.account.modelo;

import br.com.bufunfa.finance.account.modelo.Account;
import java.io.Serializable;

privileged aspect Account_Roo_Serializable {
    
    declare parents: Account implements Serializable;
    
    private static final long Account.serialVersionUID = 1L;
    
}
