// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.account.modelo;

import java.io.Serializable;

privileged aspect Transaction_Roo_Serializable {
    
    declare parents: Transaction implements Serializable;
    
    private static final long Transaction.serialVersionUID = 1L;
    
}
