// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.user.service.validation;

import br.com.bufunfa.finance.user.service.validation.UserParameters;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserParameters_Roo_Configurable {
    
    declare @type: UserParameters: @Configurable;
    
}
