// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.bufunfa.finance.user.service.validation;

import br.com.bufunfa.finance.user.service.validation.UserParameters;
import java.io.Serializable;

privileged aspect UserParameters_Roo_Serializable {
    
    declare parents: UserParameters implements Serializable;
    
    private static final long UserParameters.serialVersionUID = 1L;
    
}
